### ISSUE TITLE
Fix paths to bbn file 

### ISSUE THREAD

**Issue by EBHolm** [AarhusCosmology/connect_public#20]
Currently, if the user does not supply a path to the `bbn.data` file used by CLASS, the CONNECT data generation defaults it to `data.path['cosmo']+'/bbn/sBBN.dat'`. This is dangerous for two reasons.

* It should be the job of the CLASS implementation to specify a default BBN file, not CONNECT.
* CLASS++ and CLASS have their bbn files in different directories. In CLASS, it is in `/external/bbn`, whereas in CLASS++, it is directly in `/bbn`. This gives obvious compatibility issues.

I propose that CONNECT entirely refrains from setting the BBN file, such that the cosmo-module itself finds out which one to use.

**Comment by EBHolm** [comment]
Also, when running the iterative sampling, MontePython uses `connect.conf` whose `data.path['cosmo']` points to `connect/mp_plugin`, but there is no `bbn` folder here for when the default value `data.cosmo_arguments['sBBN_file'] = data.path['cosmo']+'/bbn/sBBN.dat'` is used.

**Comment by EBHolm** [comment]
I think the default value is set in `mp_plugin/param_templates/connect_lite_param.template`, so I believe the fix would be to simply remove line 19 from that file.

**Comment by AndreasNygaard** [comment]
Ah yes, that should of course be fixed. It is, however, not possible to prevent users from choosing a different bbn file in the parameter file for connect (and I don’t think it should be), but when using Monte Python, all of the extra cosmo arguments are completely redundant and could might as well be removed. They don’t do any harm since they connect wrapper ignores them, but I agree that it is nicer to leave them out of the Monte Python parameter file.
