### ISSUE TITLE
Let the user choose convergence criterion of iterative sampling

### ISSUE THREAD

**Issue by EBHolm** [AarhusCosmology/connect_public#23]
Currently, the convergence criterion for the iterative sampling is based on the Gelman-Rubin criterion between consecutive iterations. Therefore, the central input parameter governing "how much" data is being generated is `mp_tol`, which specifices (to my knowledge) the R-1 value between subsequent iterative chains at which the data generation halts.

I have found that the quality of this criterion depends heavily on your particular setup. For example, if the user has somewhat narrow bounds in their cosmological parameters, R-1 < 0.01 is reached very quickly and only very little data gets generated, yielding insufficient accuracies.

I therefore propose to allow the user to specify other sets of hyperparameters governing the data generation; in particular, (1) the amount of iterations and (2) the amount of points in each iteration. This way, the user can much more clearly gauge the total amount of data being created and make clearer decisions based on computation times and parameter choices.

**Comment by AndreasNygaard** [comment]
`mp_tol` is the convergence criterion for the individual MCMC samplings. `iter_tol` is the between-iterations criterion. `N_max _lines` is the maximal amount of points taken from each iteration (maximal because of the filtration to prevent oversampling of regions), and this can be increased if not much data is being generated. A very low `iter_tol` might also solve the issue.

I think it would be wrong to predetermine the number of iterations, but one could implement a “least amount of iterations” to make sure to gain enough data. If the convergence is quick, however, not much data will be gathered from subsequent iterations due to the filtration. The best option would probably be to increase `N_max_lines`.

Let me know if this was what you had in mind. If not, then I will keep the issue open.

**Comment by EBHolm** [comment]
My point was that it can be very difficult for the user to have an intuition about what values to put for `iter_tol` and `mp_tol`, whereas `N_iterations` and `N_per_iteration` are more straightforward and will never lead to the useless cases where only 1 iteration is performed (this is my current issue, and it gives poor accuracy). If I put, for example, `N_iterations = 5` and `N_per_iteration = 10**5`, I know roughly how much data I will end up with and can gauge my desired accuracy loosely based on that. In addition, CONNECT could then supply the user with the R-1 statistics to allow the user to also judge the resulting dataset based on the convergence.

Also, several clusters require the user to estimate the required amount of computation time, and this is more straightforward when inputting the absolute number of class runs ( =`N_iterations * N_per_iteration`), since with the R-1 criterion the required amount of runs can vary a lot.

Why do you think it would be wrong to predetermine the number of iterations?

**Comment by AndreasNygaard** [comment]
Even if one were to choose both the number of iterations and the amount of points from each, one could still end up with only quite few points due to filtration. If you have 5 iterations that all give the same point distribution, `connect` will remove basically all points from the last 4 iterations, since the area is well-sampled by the first iteration. If the first iterations are good anyway, you could just increase `N_max_lines` to something like 30,000. This would guarantee you at least 30,000 points from your second iteration, since the first iteration only samples 5000 points. If the initial sampling using the Latin hypercube, i.e. the first iteration, is good enough, you can also set `keep_first_iteration = True`.

The reason why predetermining the number of iterations might not be a good idea is that you are not guaranteed convergence this way. If you select 4 iterations but the iterations have not converged by then, you will end up with a network that does not represent your posterior distribution.

**Comment by EBHolm** [comment]
Quick aside: I thought `N_max_lines` was the _maximal_ amount of points that CONNECT is allowed to use for each iteration (cf. your message above)? Or is it the _minimum_ amount of points that CONNECT is forced to keep from each iteration?

_Update_: Nevermind, I figured that it is the _maximum_ amount of points that CONNECT is _forced_ to keep and that in practice it is almost always exactly the amount that CONNECT keeps.

**Comment by EBHolm** [comment]
I see and agree with your point about the problems with inputting the number of iterations and points from each iteration :)

**Comment by AndreasNygaard** [comment]
`N_max_lines` is the maximal amount from each iteration, but you are guaranteed this amount in total, since no filtration happens between first and second iterations.

The only thing that could prevent you from getting that amount of points is if the MCMC chains converge before collecting enough points. If this is indeed the case, then `mp_tol` should be decreased to perhaps 0.005.
